### ISSUE TITLE
Crossterm Input API-discussion

### ISSUE THREAD

**Issue by TimonPost** [crossterm-rs/crossterm#257]
In this issue, we will discuss all the API changes we want to make for crossterm_input.

**Comment by TimonPost** [comment]
As spoken in #249, there is probably going to change a lot with this API. But before those changes are going to be made I like to specify some minor things I like to have changed: 

Currently: 
```rust
    fn enable_mouse_mode(&self) -> Result<()>;
    fn disable_mouse_mode(&self) -> Result<()>;
    fn read_until_async(&self, delimiter: u8) -> AsyncReader;
```

To:

```rust
    fn enable_mouse_events(&self) -> Result<()>;
    fn disable_mouse_events(&self) -> Result<()>;
    fn read_until_async(&self, delimiter: char) -> AsyncReader;
```

**Comment by zrzka** [comment]
Currently, `input` depends on:

```toml
[target.'cfg(windows)'.dependencies]
winapi = { version =  "0.3.8", features = ["winnt", "winuser"] }
crossterm_winapi = { version = "0.2.1" }
```

The `crossterm_winapi` says:

> This crate provides some wrappers aground common used WinAPI functions.

Here's the idea. Shouldn't we:

* move all the parsing stuff to the `crossterm_winapi` crate,
* remove the `winapi` dependency from the `input` crate,
* interact with the `crossterm_winapi` only?

Didn't think about it thoroughly yet, it's just something that came to my mind during reviews, etc.
